version: '3.4'

services:

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  basketdb:
    image: redis:alpine

  customerdb:
    image: postgres

  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: Customer.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: OcelotAPIGateway/Dockerfile

  portainer:
    image: portainer/portainer-ce

volumes:
  postgres_data:
  mongo_data:
  portainer_data: